# Generated by Django 5.2 on 2025-04-12 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'حالة الطلب',
                'verbose_name_plural': 'حالات الطلب',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('motivation_letter', models.TextField(help_text='اشرح لماذا تريد التقدم لهذه الفرصة وما هي أهدافك', verbose_name='خطاب الدوافع')),
                ('research_proposal', models.TextField(blank=True, help_text='إذا كان الابتعاث لدراسة الدكتوراه، أرفق مقترح البحث الخاص بك', null=True, verbose_name='مقترح البحث')),
                ('comments', models.TextField(blank=True, help_text='أي معلومات إضافية تود إضافتها لطلبك', null=True, verbose_name='ملاحظات إضافية')),
                ('acceptance_letter', models.BooleanField(default=False, verbose_name='هل لديك قبول مبدئي؟')),
                ('acceptance_university', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الجامعة التي لديك قبول فيها')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='المتقدم')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='announcements.scholarship', verbose_name='فرصة الابتعاث')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.applicationstatus', verbose_name='حالة الطلب')),
            ],
            options={
                'verbose_name': 'طلب ابتعاث',
                'verbose_name_plural': 'طلبات الابتعاث',
                'ordering': ['-application_date'],
                'unique_together': {('scholarship', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='applications.application', verbose_name='الطلب')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_logs', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_logs', to='applications.applicationstatus', verbose_name='من حالة')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_logs', to='applications.applicationstatus', verbose_name='إلى حالة')),
            ],
            options={
                'verbose_name': 'سجل الطلب',
                'verbose_name_plural': 'سجلات الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المستند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المستند')),
                ('file', models.FileField(upload_to='application_documents/', verbose_name='الملف')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('is_required', models.BooleanField(default=True, verbose_name='مطلوب')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ['name'],
            },
        ),
    ]
