# Generated by Django 5.2 on 2025-04-20 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'ordering': ['order'], 'verbose_name': 'حالة الطلب', 'verbose_name_plural': 'حالات الطلبات'},
        ),
        migrations.AddField(
            model_name='application',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إدارية'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='requires_attachment',
            field=models.BooleanField(default=False, verbose_name='تتطلب مرفقات'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الحالة'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.CreateModel(
            name='ApprovalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('higher_committee', 'اللجنة العليا'), ('faculty_council', 'مجلس الكلية'), ('president', 'رئيس الجامعة')], max_length=50, verbose_name='نوع الموافقة')),
                ('attachment', models.FileField(upload_to='approvals/%Y/%m/', verbose_name='المرفق')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_attachments', to='applications.application', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مرفق موافقة',
                'verbose_name_plural': 'مرفقات الموافقات',
                'ordering': ['-upload_date'],
            },
        ),
    ]
