# Generated by Django 5.2 on 2025-05-16 11:46

import applications.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicationstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['document_type', 'upload_date'], 'verbose_name': 'مستند', 'verbose_name_plural': 'المستندات'},
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('cv', 'السيرة الذاتية'), ('personal_id', 'إثبات الهوية'), ('photo', 'صورة شخصية'), ('high_school_certificate', 'شهادة الثانوية العامة'), ('high_school_transcript', 'كشف درجات الثانوية العامة'), ('bachelors_certificate', 'شهادة البكالوريوس'), ('bachelors_transcript', 'كشف درجات البكالوريوس'), ('masters_certificate', 'شهادة الماجستير'), ('masters_transcript', 'كشف درجات الماجستير'), ('other_certificate', 'شهادة أخرى'), ('language_certificate', 'شهادة اختبار اللغة'), ('other_language_certificate', 'شهادة لغة أخرى'), ('acceptance_letter', 'خطاب القبول'), ('research_proposal', 'مقترح البحث'), ('recommendation_letter', 'رسالة توصية'), ('other', 'مستند آخر')], default='other', max_length=50, verbose_name='نوع المستند'),
        ),
        migrations.AlterField(
            model_name='approvalattachment',
            name='approval_type',
            field=models.CharField(choices=[('higher_committee', 'اللجنة العليا'), ('department_council', 'مجلس القسم'), ('faculty_council', 'مجلس الكلية'), ('deans_council', 'مجلس العمداء')], max_length=50, verbose_name='نوع الموافقة'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=applications.models.document_upload_path, verbose_name='الملف'),
        ),
        migrations.CreateModel(
            name='BachelorQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2030)], verbose_name='سنة التخرج')),
                ('country', models.CharField(max_length=100, verbose_name='بلد الدراسة')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='معلومات إضافية')),
                ('study_language', models.CharField(blank=True, choices=[('arabic', 'عربي'), ('english', 'إنجليزي'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='لغة الدراسة')),
                ('institution_name', models.CharField(max_length=200, verbose_name='اسم المؤسسة/الجامعة')),
                ('major', models.CharField(max_length=200, verbose_name='التخصص')),
                ('gpa', models.DecimalField(decimal_places=2, help_text='بالنسبة المئوية', max_digits=5, verbose_name='المعدل')),
                ('grade', models.CharField(choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جداً'), ('good', 'جيد'), ('acceptable', 'مقبول')], max_length=20, verbose_name='التقدير')),
                ('study_system', models.CharField(choices=[('regular', 'انتظام'), ('distance', 'انتساب')], max_length=20, verbose_name='نظام الدراسة')),
                ('bachelor_type', models.CharField(choices=[('regular', 'عادية'), ('bridge', 'تجسير')], max_length=20, verbose_name='نوع الشهادة')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachelor_qualifications', to='applications.application', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مؤهل البكالوريوس',
                'verbose_name_plural': 'مؤهلات البكالوريوس',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='bachelor_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.bachelorqualification', verbose_name='مؤهل البكالوريوس'),
        ),
        migrations.CreateModel(
            name='HighSchoolQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2030)], verbose_name='سنة التخرج')),
                ('country', models.CharField(max_length=100, verbose_name='بلد الدراسة')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='معلومات إضافية')),
                ('study_language', models.CharField(blank=True, choices=[('arabic', 'عربي'), ('english', 'إنجليزي'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='لغة الدراسة')),
                ('certificate_type', models.CharField(help_text='مثل: أردنية، سعودية، بكالوريا دولية، إلخ', max_length=50, verbose_name='نوع الشهادة')),
                ('branch', models.CharField(help_text='مثل: علمي، أدبي، تجاري، إلخ', max_length=50, verbose_name='الفرع/التخصص')),
                ('gpa', models.DecimalField(decimal_places=2, help_text='بالنسبة المئوية', max_digits=5, verbose_name='المعدل')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_school_qualifications', to='applications.application', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مؤهل الثانوية العامة',
                'verbose_name_plural': 'مؤهلات الثانوية العامة',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='high_school_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.highschoolqualification', verbose_name='مؤهل الثانوية العامة'),
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_english', models.BooleanField(default=True, verbose_name='اللغة الإنجليزية')),
                ('test_type', models.CharField(blank=True, choices=[('toefl_ibt', 'TOEFL iBT'), ('toefl_pbt', 'TOEFL PBT'), ('ielts', 'IELTS'), ('duolingo', 'Duolingo'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='نوع الاختبار')),
                ('other_test_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الاختبار الآخر')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاختبار')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة الكلية')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم المرجعي للاختبار')),
                ('reading_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة القراءة')),
                ('listening_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة الاستماع')),
                ('speaking_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة المحادثة')),
                ('writing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة الكتابة')),
                ('other_language', models.CharField(blank=True, choices=[('french', 'الفرنسية'), ('german', 'الألمانية'), ('spanish', 'الإسبانية'), ('chinese', 'الصينية'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='اللغة')),
                ('other_language_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم اللغة الأخرى')),
                ('proficiency_level', models.CharField(blank=True, choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('native', 'متحدث أصلي')], max_length=20, null=True, verbose_name='مستوى الإتقان')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='معلومات إضافية')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_proficiencies', to='applications.application', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'كفاءة لغوية',
                'verbose_name_plural': 'الكفاءات اللغوية',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='language_proficiency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.languageproficiency', verbose_name='الكفاءة اللغوية'),
        ),
        migrations.CreateModel(
            name='MasterQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2030)], verbose_name='سنة التخرج')),
                ('country', models.CharField(max_length=100, verbose_name='بلد الدراسة')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='معلومات إضافية')),
                ('study_language', models.CharField(blank=True, choices=[('arabic', 'عربي'), ('english', 'إنجليزي'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='لغة الدراسة')),
                ('institution_name', models.CharField(max_length=200, verbose_name='اسم المؤسسة/الجامعة')),
                ('major', models.CharField(max_length=200, verbose_name='التخصص')),
                ('gpa', models.DecimalField(decimal_places=2, help_text='بالنسبة المئوية', max_digits=5, verbose_name='المعدل')),
                ('grade', models.CharField(choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جداً'), ('good', 'جيد'), ('acceptable', 'مقبول')], max_length=20, verbose_name='التقدير')),
                ('masters_system', models.CharField(choices=[('thesis', 'مسار الرسالة'), ('comprehensive', 'مسار الشامل')], max_length=20, verbose_name='نظام الدراسة')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_qualifications', to='applications.application', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مؤهل الماجستير',
                'verbose_name_plural': 'مؤهلات الماجستير',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='master_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.masterqualification', verbose_name='مؤهل الماجستير'),
        ),
        migrations.CreateModel(
            name='OtherCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2030)], verbose_name='سنة التخرج')),
                ('country', models.CharField(max_length=100, verbose_name='بلد الدراسة')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='معلومات إضافية')),
                ('study_language', models.CharField(blank=True, choices=[('arabic', 'عربي'), ('english', 'إنجليزي'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='لغة الدراسة')),
                ('certificate_type', models.CharField(choices=[('diploma', 'دبلوم'), ('professional', 'شهادة مهنية'), ('training', 'دورة تدريبية'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الشهادة')),
                ('certificate_name', models.CharField(max_length=200, verbose_name='اسم الشهادة')),
                ('certificate_issuer', models.CharField(max_length=200, verbose_name='الجهة المانحة')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_certificates', to='applications.application', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'شهادة أخرى',
                'verbose_name_plural': 'شهادات أخرى',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='other_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.othercertificate', verbose_name='شهادة أخرى'),
        ),
    ]
