# Generated by Django 5.2 on 2025-04-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_alter_applicationstatus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الفئة')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='رمز الفئة')),
            ],
            options={
                'verbose_name': 'فئة المصروفات',
                'verbose_name_plural': 'فئات المصروفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='تاريخ التعديل')),
                ('reason', models.TextField(verbose_name='سبب التعديل')),
                ('adjustment_type', models.CharField(choices=[('increase', 'زيادة'), ('decrease', 'تخفيض')], max_length=20, verbose_name='نوع التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة التعديل')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'تعديل الميزانية',
                'verbose_name_plural': 'تعديلات الميزانية',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='تاريخ المصروف')),
                ('description', models.TextField(verbose_name='وصف المصروف')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الإيصال')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='finance/receipts/%Y/%m/', verbose_name='ملف الإيصال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة المصروف')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة/الرفض')),
                ('approval_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الموافقة/الرفض')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة/الرفض بواسطة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='فئة المصروف')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف التقرير')),
                ('report_type', models.CharField(choices=[('budget_summary', 'ملخص الميزانية'), ('expense_summary', 'ملخص المصروفات'), ('budget_comparison', 'مقارنة الميزانيات'), ('monthly_expenses', 'المصروفات الشهرية'), ('category_expenses', 'المصروفات حسب الفئة'), ('custom', 'تقرير مخصص')], max_length=50, verbose_name='نوع التقرير')),
                ('filters', models.JSONField(blank=True, null=True, verbose_name='فلاتر التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_public', models.BooleanField(default=False, verbose_name='متاح للجميع')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير مالي',
                'verbose_name_plural': 'التقارير المالية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الإجمالي')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء الميزانية')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الميزانية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('tuition_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرسوم الدراسية')),
                ('monthly_stipend', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المخصص الشهري')),
                ('travel_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل السفر')),
                ('health_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='التأمين الصحي')),
                ('books_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل الكتب')),
                ('research_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل البحث العلمي')),
                ('conference_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل المؤتمرات')),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مصاريف أخرى')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('suspended', 'معلقة'), ('closed', 'مغلقة')], default='active', max_length=20, verbose_name='حالة الميزانية')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='applications.application', verbose_name='طلب الابتعاث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'ميزانية الابتعاث',
                'verbose_name_plural': 'ميزانيات الابتعاث',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('approve', 'موافقة'), ('reject', 'رفض')], max_length=20, verbose_name='نوع العملية')),
                ('description', models.TextField(verbose_name='وصف العملية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finance.budgetadjustment', verbose_name='تعديل الميزانية')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_logs', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finance.expense', verbose_name='المصروف')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finance.scholarshipbudget', verbose_name='الميزانية')),
            ],
            options={
                'verbose_name': 'سجل مالي',
                'verbose_name_plural': 'السجلات المالية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.scholarshipbudget', verbose_name='الميزانية'),
        ),
        migrations.AddField(
            model_name='budgetadjustment',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='finance.scholarshipbudget', verbose_name='الميزانية'),
        ),
    ]
