# Generated by Django 5.2 on 2025-05-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_insurance_rate', models.DecimalField(decimal_places=4, default=0.0034, help_text='3.4/1000', max_digits=6, verbose_name='معدل التأمين على الحياة')),
                ('add_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='نسبة الزيادة على المجموع الكلي (%)', max_digits=5, verbose_name='نسبة الزيادة')),
            ],
            options={
                'verbose_name': 'إعدادات نظام الابتعاث',
                'verbose_name_plural': 'إعدادات نظام الابتعاث',
            },
        ),
        migrations.AddField(
            model_name='scholarshipbudget',
            name='academic_year',
            field=models.CharField(default='2024-2025', help_text='مثال: 2024-2025', max_length=9, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='scholarshipbudget',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0.91, help_text='سعر صرف العملة الأجنبية', max_digits=6, verbose_name='سعر الصرف'),
        ),
        migrations.AddField(
            model_name='scholarshipbudget',
            name='foreign_currency',
            field=models.CharField(default='GBP', max_length=3, verbose_name='العملة الأجنبية'),
        ),
        migrations.AddField(
            model_name='scholarshipbudget',
            name='is_current',
            field=models.BooleanField(default=True, help_text='هل هذه الميزانية للسنة الحالية؟', verbose_name='السنة الحالية'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='report_type',
            field=models.CharField(choices=[('budget_summary', 'ملخص الميزانية'), ('expense_summary', 'ملخص المصروفات'), ('budget_comparison', 'مقارنة الميزانيات'), ('monthly_expenses', 'المصروفات الشهرية'), ('category_expenses', 'المصروفات حسب الفئة'), ('scholarship_years_costs', 'تكاليف الابتعاث حسب السنوات'), ('custom', 'تقرير مخصص')], max_length=50, verbose_name='نوع التقرير'),
        ),
        migrations.CreateModel(
            name='YearlyScholarshipCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.PositiveIntegerField(help_text='رقم السنة من الابتعاث (1, 2, 3, ...)', verbose_name='رقم السنة')),
                ('academic_year', models.CharField(help_text='مثال: 2024-2025', max_length=9, verbose_name='السنة الدراسية')),
                ('travel_tickets', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تذكرة سفر')),
                ('monthly_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المخصص الشهري')),
                ('monthly_duration', models.PositiveIntegerField(default=12, verbose_name='عدد الأشهر')),
                ('visa_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم الفيزا')),
                ('health_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التأمين الصحي')),
                ('tuition_fees_local', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرسوم الدراسية (بالدينار)')),
                ('tuition_fees_foreign', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرسوم الدراسية (بالعملة الأجنبية)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_costs', to='finance.scholarshipbudget', verbose_name='الميزانية')),
            ],
            options={
                'verbose_name': 'تكاليف سنوية للابتعاث',
                'verbose_name_plural': 'التكاليف السنوية للابتعاث',
                'ordering': ['year_number'],
                'unique_together': {('budget', 'year_number')},
            },
        ),
    ]
