# Generated by Django 5.2 on 2025-05-16 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_scholarshipsettings_scholarshipbudget_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiallog',
            name='action_type',
            field=models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('approve', 'موافقة'), ('reject', 'رفض'), ('close', 'إغلاق')], max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='report_type',
            field=models.CharField(choices=[('budget_summary', 'ملخص الميزانية'), ('expense_summary', 'ملخص المصروفات'), ('budget_comparison', 'مقارنة الميزانيات'), ('monthly_expenses', 'المصروفات الشهرية'), ('category_expenses', 'المصروفات حسب الفئة'), ('scholarship_years_costs', 'تكاليف الابتعاث حسب السنوات'), ('fiscal_year_summary', 'ملخص السنة المالية'), ('custom', 'تقرير مخصص')], max_length=50, verbose_name='نوع التقرير'),
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='السنة المالية')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=10, verbose_name='الحالة')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي الميزانية السنوية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف/ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fiscal_years', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'السنة المالية',
                'verbose_name_plural': 'السنوات المالية',
                'ordering': ['-year'],
                'unique_together': {('year',)},
            },
        ),
        migrations.AddField(
            model_name='budgetadjustment',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_adjustments', to='finance.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='expense',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='financiallog',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_logs', to='finance.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='finance.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='scholarshipbudget',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_budgets', to='finance.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='scholarshipsettings',
            name='current_fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.fiscalyear', verbose_name='السنة المالية الحالية'),
        ),
        migrations.AddField(
            model_name='yearlyscholarshipcosts',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearly_scholarship_costs', to='finance.fiscalyear', verbose_name='السنة المالية'),
        ),
    ]
