# Generated by Django 5.2 on 2025-05-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_financiallog_action_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipbudget',
            name='books_allowance',
        ),
        migrations.RemoveField(
            model_name='scholarshipbudget',
            name='conference_allowance',
        ),
        migrations.RemoveField(
            model_name='scholarshipbudget',
            name='health_insurance',
        ),
        migrations.RemoveField(
            model_name='scholarshipbudget',
            name='monthly_stipend',
        ),
        migrations.RemoveField(
            model_name='scholarshipbudget',
            name='other_expenses',
        ),
        migrations.RemoveField(
            model_name='scholarshipbudget',
            name='research_allowance',
        ),
        migrations.RemoveField(
            model_name='scholarshipbudget',
            name='travel_allowance',
        ),
        migrations.RemoveField(
            model_name='scholarshipbudget',
            name='tuition_fees',
        ),
    ]
