# Generated by Django 5.2 on 2025-05-25 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_scholarshipbudget_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approval_notes',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipt_file',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='إيصال المصروف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
