# Generated by Django 5.2 on 2025-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الودجة')),
                ('widget_type', models.CharField(choices=[('applications_stats', 'إحصائيات الطلبات'), ('scholarship_stats', 'إحصائيات فرص الابتعاث'), ('evaluations_stats', 'إحصائيات التقييمات'), ('recent_applications', 'آخر الطلبات'), ('recent_scholarships', 'آخر فرص الابتعاث'), ('recent_evaluations', 'آخر التقييمات'), ('status_chart', 'مخطط حالات الطلبات'), ('committee_chart', 'مخطط تقييمات اللجان')], max_length=30, verbose_name='نوع الودجة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('show_to_roles', models.CharField(help_text='أدوار المستخدمين الذين سيشاهدون هذه الودجة، مفصولة بفواصل', max_length=200, verbose_name='ظهور للأدوار')),
            ],
            options={
                'verbose_name': 'ودجة لوحة التحكم',
                'verbose_name_plural': 'ودجات لوحة التحكم',
                'ordering': ['order'],
            },
        ),
    ]
