# Generated by Django 5.2 on 2025-04-11 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الكلية')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز الكلية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز القسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.faculty', verbose_name='الكلية')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['faculty__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('role', models.CharField(choices=[('student', 'طالب'), ('faculty', 'عضو هيئة تدريس'), ('admin', 'مشرف نظام'), ('committee', 'عضو لجنة')], default='student', max_length=20, verbose_name='الدور')),
                ('academic_rank', models.CharField(choices=[('assistant_prof', 'أستاذ مساعد'), ('associate_prof', 'أستاذ مشارك'), ('professor', 'أستاذ'), ('lecturer', 'محاضر'), ('na', 'غير منطبق')], default='na', max_length=20, verbose_name='الرتبة الأكاديمية')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة شخصية')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='الصورة الشخصية')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='القسم')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.faculty', verbose_name='الكلية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف شخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
    ]
