# Generated by Django 5.2 on 2025-04-12 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'نوع الابتعاث',
                'verbose_name_plural': 'أنواع الابتعاث',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تم الإنشاء في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تم التحديث في')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='تم إنشاؤه بواسطة')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('requirements', models.TextField(verbose_name='المتطلبات')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='المميزات')),
                ('countries', models.CharField(blank=True, max_length=255, null=True, verbose_name='الدول المتاحة')),
                ('universities', models.TextField(blank=True, null=True, verbose_name='الجامعات المتاحة')),
                ('deadline', models.DateTimeField(verbose_name='الموعد النهائي للتقديم')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('closed', 'مغلق')], default='draft', max_length=20, verbose_name='الحالة')),
                ('max_applicants', models.PositiveIntegerField(default=0, help_text='0 يعني غير محدود', verbose_name='الحد الأقصى للمتقدمين')),
                ('eligibility_criteria', models.TextField(blank=True, null=True, verbose_name='معايير الأهلية')),
                ('application_process', models.TextField(blank=True, null=True, verbose_name='عملية التقديم')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='معلومات الاتصال')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='scholarship_attachments/', verbose_name='مرفق')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تم التحديث في')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scholarships', to=settings.AUTH_USER_MODEL, verbose_name='تم إنشاؤه بواسطة')),
                ('scholarship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='announcements.scholarshiptype', verbose_name='نوع الابتعاث')),
            ],
            options={
                'verbose_name': 'فرصة ابتعاث',
                'verbose_name_plural': 'فرص الابتعاث',
                'ordering': ['-publication_date'],
            },
        ),
    ]
